spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/events?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation : true
        format_sql : true

logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type :
          descriptor:
            sql:
              BasicBinder : TRACE

swagger:
  index: /swagger-ui/index.html#
  event:
    create: /swagger-ui/index.html#/Event%20Controller/createUsingPOST
    readAll: /swagger-ui/index.html#/Event%20Controller/readAllUsingGET
    read: /swagger-ui/index.html#/Event%20Controller/readUsingGET
    update : /swagger-ui/index.html#/Event%20Controller/updateUsingPUT